# Generated by Django 3.0 on 2022-04-04 09:58

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NormalUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('photo', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='email address')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_type', models.CharField(choices=[('ANDROID', 'ANDROID'), ('FULLSTACK', 'FULLSTACK')], default=0, max_length=9)),
                ('project_landingpage', cloudinary.models.CloudinaryField(default='image', max_length=255, verbose_name='image')),
                ('project_description', models.TextField()),
                ('project_owner', models.CharField(max_length=100)),
                ('project_member1', models.CharField(blank=True, max_length=50, null=True)),
                ('project_member2', models.CharField(blank=True, max_length=50, null=True)),
                ('project_member3', models.CharField(blank=True, max_length=50, null=True)),
                ('project_member4', models.CharField(blank=True, max_length=50, null=True)),
                ('project_member5', models.CharField(blank=True, max_length=50, null=True)),
                ('project_member6', models.CharField(blank=True, max_length=50, null=True)),
                ('github_link', models.URLField(max_length=100)),
            ],
        ),
    ]
