# Generated by Django 3.0 on 2022-04-01 12:36

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_type', models.CharField(choices=[('ANDROID', 'ANDROID'), ('FULLSTACK', 'FULLSTACK')], max_length=9)),
                ('project_description', models.TextField()),
                ('project_owner', models.TextField()),
                ('project_members', jsonfield.fields.JSONField(default=dict)),
                ('github_link', models.URLField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
