# Generated by Django 3.0 on 2022-04-01 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220401_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='project_members',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='project_type',
        ),
    ]
