# Generated by Django 3.0 on 2022-04-01 13:13

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220401_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_members',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_type',
            field=models.CharField(choices=[('ANDROID', 'ANDROID'), ('FULLSTACK', 'FULLSTACK')], default=0, max_length=9),
        ),
    ]
