# Generated by Django 3.0 on 2022-04-03 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220403_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_member',
            new_name='project_members',
        ),
    ]
