# Generated by Django 3.0 on 2022-04-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20220403_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_member',
            new_name='project_member1',
        ),
        migrations.AddField(
            model_name='project',
            name='project_member2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_member3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_member4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_member5',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_member6',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
