# Generated by Django 3.0 on 2022-04-04 09:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20220403_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_landingpage',
            field=cloudinary.models.CloudinaryField(default='image', max_length=255, verbose_name='image'),
        ),
    ]
